language: python
sudo: required
dist: xenial
python: "3.7"

env:
- DJANGO_VERSION=2.1.5
  global:
   - SECRET_KEY=verysecret
   - DEBUG_MODE=True
   - DB_NAME=testdb
   - DB_USER_NAME=postgres
   - DB_PASSWORD=secpassword

install:
- pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - python manage.py migrate

script:
- python manage.py test