language: python
sudo: required
dist: xenial
python: "3.7"

env:
  global:
   - DJANGO_VERSION=2.1.5
   - SECRET_KEY=verysecret
   - DEBUG_MODE=True
   - DB_NAME=test_db
   - DB_USER_NAME=postgres
   - DB_PASSWORD=''

services:
  - postgresql

install:
- pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - python manage.py migrate

script:
- python manage.py test