# Generated by Django 2.1.5 on 2019-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default='2019-01-23'),
            preserve_default=False,
        ),
    ]
