# Generated by Django 2.1.5 on 2019-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('SC', 'scheduled'), ('IN', 'in progress'), ('CO', 'completed')], default='SC', max_length=2),
        ),
    ]
